import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    ignores: [
      // generated by `react-router typegen` (part of `bun run typecheck`)
      ".react-router/",
      "app/routes/+types/",
      "build/",
      // logos and self-hosted fonts are assets, not JS
      "assets/",
      // no JSON plugin configured; package.json/tsconfig are read by tsc
      "**/*.json",
    ],
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    plugins: { js },
    extends: ["js/recommended"],
    languageOptions: {
      // SSR (react-router.config.ts ssr: true) plus Vite config files at the root
      globals: { ...globals.browser, ...globals.node },
    },
  },
  tseslint.configs.recommended,
  {
    // No eslint-plugin-react: its rules are prop-types/JSX-in-scope/display-name
    // shaped, all dead under React 19 + the automatic JSX runtime + TypeScript,
    // and its version-detect path crashes on ESLint 10. react-hooks is the part
    // that catches real bugs. Add it back if a rule here proves it earns its keep.
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // React Router's own signature for a route that reads no meta args:
      //   export function meta({}: Route.MetaArgs)
      // an empty destructure IS the documented shape, not a mistake
      "no-empty-pattern": "off",
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
]);